<a href="https://colab.research.google.com/github/solielmaf/pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Creating Tensor


In [4]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [5]:
# dimensions of the tensor
scalar.ndim


0

In [6]:
# get tensor back as python init
scalar.item()

5

In [7]:
#Vector
vector=torch.tensor([2,2])
vector

tensor([2, 2])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector[0].item()

2

In [11]:
#Matrix
MATRIX = torch.tensor([[2,3],[4,2]])
MATRIX

tensor([[2, 3],
        [4, 2]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[[1,1,2],[3,4,4],[4,7,9]],[[1,2,2],[3,3,3],[4,3,5]]]])
TENSOR

tensor([[[[1, 1, 2],
          [3, 4, 4],
          [4, 7, 9]],

         [[1, 2, 2],
          [3, 3, 3],
          [4, 3, 5]]]])

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

In [ ]:
TENSOR.ndim

4

### Random Tensors

In [ ]:
random_tens =torch.rand(5,3,2)
random_tens

tensor([[[0.8957, 0.7543],
         [0.8452, 0.9402],
         [0.3508, 0.9742]],

        [[0.1357, 0.0708],
         [0.8789, 0.2145],
         [0.6694, 0.1716]],

        [[0.9840, 0.2027],
         [0.1130, 0.4929],
         [0.4349, 0.2729]],

        [[0.6302, 0.8972],
         [0.3335, 0.0330],
         [0.6807, 0.0494]],

        [[0.8506, 0.8148],
         [0.2679, 0.3730],
         [0.0322, 0.9371]]])

In [ ]:
## Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,244,244)) # color channel ,h,w
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and Ones


In [12]:
zeros = torch.zeros(3,2)
ones = torch.ones(3,2)
zeros,ones

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [13]:
ones.dtype

torch.float32

### Range of Tensors and Tensors-like

In [15]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
one_to_ten=torch.arange(0,10,2)
one_plus=torch.ones_like(input=one_to_ten  )
one_to_ten, one_plus

(tensor([0, 2, 4, 6, 8]), tensor([1, 1, 1, 1, 1]))

### Tensor datatypes

In [25]:
float_32_tensor = torch.tensor([3.0,4.0,3.0], dtype=None ,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 4., 3.])

In [21]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 4., 3.], dtype=torch.float16), torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 16.,  9.])

In [26]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.long)
int_32_tensor

tensor([3, 4, 5])

tensor.shape
tensor.device
tensor.dtype