<a href="https://colab.research.google.com/github/solielmaf/pytorch/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [3]:
!nvidia-smi

Sat Oct  4 06:37:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Creating Tensor


In [ ]:
#scalar
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
# dimensions of the tensor
scalar.ndim


0

In [ ]:
# get tensor back as python init
scalar.item()

5

In [ ]:
#Vector
vector=torch.tensor([2,2])
vector

tensor([2, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[0].item()

2

In [ ]:
#Matrix
MATRIX = torch.tensor([[2,3],[4,2]])
MATRIX

tensor([[2, 3],
        [4, 2]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[[1,1,2],[3,4,4],[4,7,9]],[[1,2,2],[3,3,3],[4,3,5]]]])
TENSOR

tensor([[[[1, 1, 2],
          [3, 4, 4],
          [4, 7, 9]],

         [[1, 2, 2],
          [3, 3, 3],
          [4, 3, 5]]]])

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

In [ ]:
TENSOR.ndim

4

### Random Tensors

In [ ]:
random_tens =torch.rand(5,3,2)
random_tens

tensor([[[0.8957, 0.7543],
         [0.8452, 0.9402],
         [0.3508, 0.9742]],

        [[0.1357, 0.0708],
         [0.8789, 0.2145],
         [0.6694, 0.1716]],

        [[0.9840, 0.2027],
         [0.1130, 0.4929],
         [0.4349, 0.2729]],

        [[0.6302, 0.8972],
         [0.3335, 0.0330],
         [0.6807, 0.0494]],

        [[0.8506, 0.8148],
         [0.2679, 0.3730],
         [0.0322, 0.9371]]])

In [ ]:
## Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,244,244)) # color channel ,h,w
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and Ones


In [ ]:
zeros = torch.zeros(3,2)
ones = torch.ones(3,2)
zeros,ones

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [ ]:
ones.dtype

torch.float32

### Range of Tensors and Tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(0,10,2)
one_plus=torch.ones_like(input=one_to_ten  )
one_to_ten, one_plus

(tensor([0, 2, 4, 6, 8]), tensor([1, 1, 1, 1, 1]))

### Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0,4.0,3.0], dtype=None ,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 4., 3.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 4., 3.], dtype=torch.float16), torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 16.,  9.])

In [ ]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.long)
int_32_tensor

tensor([3, 4, 5])

tensor.shape

tensor.device

tensor.dtype

### Manipulating Tensors

In [2]:
# Addition  can be torch.add(a,b)
tensor = torch.tensor([2,2,3])
tensor + 10

tensor([12, 12, 13])

In [6]:
#  myltiply tensor can be torch.mul(a,b)
tensor * 10, torch.mul(tensor,10)

(tensor([20, 20, 30]), tensor([20, 20, 30]))

### Matrix multiplication
two main ways of  matrix multiplication in neural network  and deep learning
1. Element wise multiplication
2. Matrix multiplication   (Dot product)

2 rules
1 inner dimension should match

 - (3,2) @ (2,3)

2 resulting is same outer shape

  - (3,3)


In [7]:
# element wise

tensor([4, 4, 9])

In [8]:
#matrix torch.mm(a,b)
torch.matmul(tensor,tensor)

tensor(17)

to fix tensor shape error we can **transpose** (.T) to switch the dimensions

In [11]:
tensor =torch.rand(3,2)
tensor.T

tensor([[0.1321, 0.3272, 0.8749],
        [0.2417, 0.1194, 0.0092]])

## Finding min,max,mean, sum, etc (tensor aggregation)

In [2]:
# tensor.mean need float type
x = torch.arange(0,100,10).type(torch.float32)
x.min(), torch.min(x),x.max(),x.mean(), torch.mean(x),x.sum(),x


(tensor(0.),
 tensor(0.),
 tensor(90.),
 tensor(45.),
 tensor(45.),
 tensor(450.),
 tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [3]:
# the index of min max
x.argmax(), x.argmin(), x.argsort()

(tensor(9), tensor(0), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

 ### Reshaping, stacking , squeezing and unsqueezing tensor
  - Reshaping - reshapes an input tensor to a defined shape
  - view- return a view of an input tensor of certain shape but keep the same memory as the first
  - stacking - combine multiple tensors on top of each other (concatination) v stack , hstack
  - squeezing - removes one dimensions from tenosr
  - unsqueezing- add a 1 dimension to target tensor
  - Permute- return a view of the input with dimesions permuted (swapped) in certain way

In [30]:
X= torch.arange(0.,10.)
X_reshaped = X.reshape(5,2)
X_reshaped, X



(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [33]:
z = X.view(1,10)
z[:,2]=5
z, z.shape, X

(tensor([[0., 1., 5., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 10]),
 tensor([0., 1., 5., 3., 4., 5., 6., 7., 8., 9.]))

In [21]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_hstacked = torch.hstack([x,x,x,x] )
x_stacked,x_hstacked.shape

(tensor([[ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
         [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
         [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
         [ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]]),
 torch.Size([40]))

In [22]:
x_squeezed = X_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [26]:
y=torch.rand(2,5,6)
x_permuted = torch.permute(y,(1,0,2))
x_permuted, x_permuted.shape

(tensor([[[0.4623, 0.6892, 0.6438, 0.0221, 0.8487, 0.0819],
          [0.1751, 0.7423, 0.7370, 0.5795, 0.6542, 0.3716]],
 
         [[0.0160, 0.3868, 0.6167, 0.3593, 0.8184, 0.8022],
          [0.0671, 0.2845, 0.9138, 0.1435, 0.1882, 0.9217]],
 
         [[0.6647, 0.7604, 0.0459, 0.9302, 0.3390, 0.4482],
          [0.6480, 0.3040, 0.1677, 0.4233, 0.5728, 0.2323]],
 
         [[0.5171, 0.8877, 0.7934, 0.4369, 0.5179, 0.4663],
          [0.0652, 0.2111, 0.3652, 0.3409, 0.6808, 0.3689]],
 
         [[0.4407, 0.1518, 0.6969, 0.6070, 0.4981, 0.7027],
          [0.6778, 0.4168, 0.8054, 0.1332, 0.6611, 0.5824]]]),
 torch.Size([5, 2, 6]))

In [34]:
x_original= torch.rand(244,244,3)
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 244, 244])

### Indexing
indexing with PyTorch is similar to numpy

In [47]:
x= torch.arange(1,10).reshape(1,3,3)
x= x.squeeze()
x[2][2],x[0]

(tensor(9), tensor([1, 2, 3]))

 ## Pytorch tensors and NumPy
 NumPy is scientific  Python numerical computing library

torch.from_numpy(ndarray)

torch.Tensor.numpy()

In [52]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [57]:
tensor = torch.ones(7)
numpy_tensor= tensor.numpy()
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

 ## Reproduciblity (trying to take random out of random)
 neural network learns:

 start with rand np.number -> tensor operations -> update the rand number and make them better representation of the data -> again -> AggregationType

to reduce randomness in neural network and pytorch " random seed"

random seed does flavor the randomness

In [58]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3426, 0.8062, 0.3270, 0.6138],
        [0.2152, 0.3771, 0.4817, 0.7042],
        [0.5852, 0.3067, 0.6263, 0.6733]])
tensor([[0.1685, 0.3742, 0.7811, 0.7037],
        [0.9888, 0.0925, 0.4008, 0.5933],
        [0.3764, 0.4629, 0.1089, 0.9861]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [2]:
RANDOME_SEED = 42
torch.manual_seed(RANDOME_SEED)
random_tens_a = torch.rand(3,4)
torch.manual_seed(RANDOME_SEED)
random_tens_b = torch.rand(3,4)
print(random_tens_a)
print(random_tens_b)
print(random_tens_a == random_tens_b)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch  object on the GPUs

In [3]:
!nvidia-smi

Fri Oct  3 17:44:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## checking GPU acces with pyTorch

In [4]:
torch.cuda.is_available()

True

In [5]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

### Putting tensors(and models) on the Gpu

In [7]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to CPU

In [10]:
# NumPy on works on cpu

tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])